services:
  db:
    image: mongo:latest
    container_name: booking_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: booking_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://db:27017/seat_booking_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: booking_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: